# -*- coding: utf-8 -*-
"""uprise_data standardization and retrieval

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1boTb9YMf-cuWY-QJ6tb2zRGpZmrzsbho
"""

import pandas as pd
uprise_data = pd.read_excel("/content/drive/MyDrive/uprise all data.xlsx")

import numpy as np

uprise_data.head(10)

# Standardize 'Crop' column by stripping whitespace and converting to lowercase
uprise_data['Crop'] = uprise_data['Crop'].astype(str).str.strip().str.lower()

# Convert all variations of 'sorghum' (e.g., those starting with 'so') to 'sorghum'
uprise_data['Crop'] = np.where(uprise_data['Crop'].str.startswith('so'), 'sorghum', uprise_data['Crop'])

uprise_data['Crop'].value_counts()

df = uprise_data.copy()
# make everything in the daatframe alower
df = df.applymap(lambda s: s.lower() if type(s) == str else s)

# cleaning

df = df.drop(columns=df.columns[28:], axis=1)
df = df.drop(columns='Country.1', axis=1)
#replace sample id column withnid
df.rename(columns={'Country sample ID': 'Id', }, inplace=True)
df.index = df['Id']

print(df.columns)

column_map= {'Fungicide': 'Biocide', 'Mixed Cropping': 'Mixcrop', 'Seed': 'Seedprep', 'AFLA (ppb)': 'Afla', 'FUM(ppb)': 'Fum', 'OTA(ppb)': 'Ota', 'ZEA (ppb)': 'Zen',
       'DON (ppb)': 'Don','SowingMethod':'Sowmethod', 'PrevoiusTime':'Prevtime', 'PreviousCrop':'Prevcrop'}

df.rename(columns=column_map, inplace=True)
df.columns

df1= df.drop(columns=['TestDate','Soil','HarvestDate', 'Variety'], axis=1)
#rename sowingdate with harvest column
df1.rename(columns={'SamplingDate': 'HarvestDate'}, inplace=True)
df1.columns
#

# Convert relevant columns to numeric, coercing errors will turn non-convertible values into NaN
for col in ['Afla', 'Fum', 'Ota', 'Zen', 'Don']:
    df1[col] = pd.to_numeric(df1[col], errors='coerce')

# Now that 'Fum' is guaranteed to be numeric (or NaN), perform the division
#df1['Fum']= df1['Fum']/100

g1=df1.groupby(['Country','Crop'])[['Afla', 'Fum', 'Ota', 'Zen', 'Don']].mean()

print(g1)
plot = g1.plot(kind='bar')

#
print(df1['Country'].value_counts())
print('='*60)
print(df1['Crop'].value_counts())
print('='*60)
print(df1['Awareness'].value_counts())
print('='*60)
print(df1.groupby('Country')[['Region']].value_counts())
print('='*60)
print(df1.groupby(['Crop'])[['Color']].value_counts())
print('='*60)
print(df1.groupby(['Country'])[['Crop']].value_counts())

import pandas as pd
import re
import calendar

def clean_sowing_date(date_col, is_start=True):

    def parse_date(x):

        if pd.isna(x):
            return pd.NaT

        x = str(x).lower().strip()

        # remove invalid entries
        if x in ["notapplied","n/a","na","none","virgin land",""]:
            return pd.NaT

        # remove descriptive words
        x = re.sub(r'\b(early|mid|late|end|beginning|of)\b', '', x)

        # remove ordinal suffix
        x = re.sub(r'(\d+)(st|nd|rd|th)', r'\1', x)

        # handle ranges (take first part)
        if " - " in x:
            x = x.split(" - ")[0]

        # remove timestamp if present
        x = x.split(" ")[0]

        # convert using pandas
        dt = pd.to_datetime(x, errors='coerce', dayfirst=False)

        if pd.isna(dt):
            return pd.NaT

        # if month-year only (day=1 automatically)
        if dt.day == 1 and re.match(r'^[a-z]{3}-\d{2}$', x):
            if is_start:
                return pd.Timestamp(dt.year, dt.month, 1)
            else:
                last_day = calendar.monthrange(dt.year, dt.month)[1]
                return pd.Timestamp(dt.year, dt.month, last_day)

        return dt

    return date_col.apply(parse_date)

crop_map = {

# cereals
"maize": "cereal",
"sorghum": "cereal",
"millet": "cereal",
"millet ": "cereal",
" millet": "cereal",
"cereal": "cereal",

# cotton
"cotton": "cottonflower",
"coton": "cottonflower",

# legumes
"soybean": "legume",
"beans": "legume",
"bean": "legume",
"cowpea": "legume",
"cowpeas": "legume",
"peanut": "legume",
"peanuts": "legume",
"legume": "legume",

# tubers
"yam": "tuber",
"cassava": "tuber",
"potatoes": "tuber",
"tuber": "tuber",

# uncultivated / other
"nothing": "uncultivated",
"uncultivated": "uncultivated",
"mix": "mix",
"fruit": "fruit",
"fruits": "fruit",
"sunflower": "cottonflower",
"mellon": "fruit",
"tomatoes": "fruit",
"poultry": "uncultivated"
}

crop_map

df1['Harvestdate']=clean_sowing_date(df1['HarvestDate'], is_start=False)
df1['Sowdate']=clean_sowing_date(df1['SowingDate'])
# print the harvest date and country column but only row where country is nigeria
print(df1.loc[df1['Country'].str.lower() == 'benin', ['Country', 'Harvestdate','HarvestDate', 'Sowdate','SowingDate']])
df1.drop(columns=['HarvestDate','SowingDate'], inplace=True)
df1.columns
#

df1['Prevcrop'].value_counts()

df1['Prevcrop']=df1['Prevcrop'].str.lower().str.strip()
#rename prevcrop column items with the crop map
df1['Prevcrop'] = df1['Prevcrop'].replace(crop_map)

df1['Prevcrop'].unique()
for i,j in enumerate(df1['Prevcrop']):
  if j not in ['cereal', 'mix', 'cottonflower', 'legume', 'tuber', 'uncultivated']:
    print(i,j)

# Replace the item at integer location 21 in 'Prevcrop' column with 'cereal'
df1['Prevcrop'].iloc[21] = 'cereal'
df1['Prevcrop'].iloc[264] = 'cereal'
df1['Prevcrop'].iloc[312] = 'cereal'
df1['Prevcrop'].iloc[373] = 'cereal'
df1['Prevcrop'].iloc[256] = 'legume'

# Verify the change

print(df1['Prevcrop'].value_counts())

df1.columns
df1['Country']

# Identify rows for Kenya
kenya_rows_mask = df1['Country'] == 'kenya'

# Temporarily store original 'Latitude' values for Kenya rows
original_kenya_latitude = df1.loc[kenya_rows_mask, 'Latitude'].copy()

# Assign 'Longitude' values to 'Latitude' for Kenya rows
df1.loc[kenya_rows_mask, 'Latitude'] = df1.loc[kenya_rows_mask, 'Longitude']

# Assign original 'Latitude' values to 'Longitude' for Kenya rows
df1.loc[kenya_rows_mask, 'Longitude'] = original_kenya_latitude

print("Columns 'Latitude' and 'Longitude' swapped for Kenya data.")

# Display a sample of the Kenya data to verify the swap
display(df1.loc[kenya_rows_mask, ['Country', 'Latitude', 'Longitude']].head())

# Identify rows for Kenya
enya_rows_mask = df1['Country'] == 'southafrica'

# Temporarily store original 'Latitude' values for Kenya rows
riginal_kenya_latitude = df1.loc[enya_rows_mask, 'Latitude'].copy()

# Assign 'Longitude' values to 'Latitude' for Kenya rows
df1.loc[enya_rows_mask, 'Latitude'] = df1.loc[enya_rows_mask, 'Longitude']

# Assign original 'Latitude' values to 'Longitude' for Kenya rows
df1.loc[enya_rows_mask, 'Longitude'] = riginal_kenya_latitude

print("Columns 'Latitude' and 'Longitude' swapped for Kenya data.")
# Display a sample of the Kenya data to verify the swap
display(df1.loc[enya_rows_mask, ['Country', 'Latitude', 'Longitude']].head())

len(df1.loc[df1['Country']=='southafrica','Latitude'])



import re

def clean_coordinate(coord):
    if pd.isna(coord):
        return None

    coord = str(coord).strip().replace(',', '.')  # replace comma with decimal point
    coord_upper = coord.upper()  # for consistent hemisphere detection

    # === DMS format: 9°27'28.9'' N or 37*47'3.768"E ===
    dms_match = re.match(r"(\d+)[°*](\d+)['](\d+(?:\.\d+)?)[\"’]? *([NSEWnsew])?", coord_upper)
    if dms_match:
        deg, mins, secs, hemi = dms_match.groups()

        val = float(deg) + float(mins)/60 + float(secs)/3600
        if hemi in ['S', 'W', 's', 'w']:
            val = -val
        return val

    # === Decimal degrees: 10.771847°N ===
    dec_match = re.match(r"([-+]?\d+(?:\.\d+)?)[°]?[ ]*([NSEW])?", coord_upper)
    if dec_match:
        val, hemi = dec_match.groups()
        val = float(val)
        if hemi in ['S', 'W']:
            val = -val
        return val

    # === Fallback: extract first numeric value and apply hemisphere ===
    nums = re.findall(r"[-+]?\d*\.\d+|\d+", coord)
    if nums:
        val = float(nums[0])
        if 'S' in coord_upper or 'W' in coord_upper:
            val = -val
        return val

    # Could not parse
    return None

import re

def clean_coordinate(coord):
    if pd.isna(coord):
        return None

    coord = str(coord).strip().replace(',', '.')  # replace comma with decimal
    coord_upper = coord.upper()

    # === Detect hemisphere from the last character if it is a letter ===
    hemi = coord_upper[-1] if coord_upper[-1] in ['N', 'S', 'E', 'W'] else None

    # === DMS format: 9°27'28.9'' N or 37*47'3.768"E ===
    dms_match = re.match(r"(\d+)[°*](\d+)['](\d+(?:\.\d+)?)[\"’]?", coord_upper)
    if dms_match:
        deg, mins, secs = dms_match.groups()
        val = float(deg) + float(mins)/60 + float(secs)/3600
        if hemi in ['S', 'W']:
            val = -val
        return val

    # === Decimal degrees: 10.771847°N ===
    dec_match = re.match(r"([-+]?\d+(?:\.\d+)?)[°]?", coord_upper)
    if dec_match:
        val = float(dec_match.groups()[0])
        if hemi in ['S', 'W']:
            val = -val
        return val

    # === Fallback: extract first numeric value and apply hemisphere ===
    nums = re.findall(r"[-+]?\d*\.\d+|\d+", coord_upper)
    if nums:
        val = float(nums[0])
        if hemi in ['S', 'W']:
            val = -val
        return val

    return None

# CLEAN COORDINATES ##


import pandas as pd
import re


# === Function to clean coordinates ===
def clean_coordinate(coord):
    if pd.isna(coord):
        return None
    # Extract numeric part
    num = re.findall(r"[-+]?\d*\.\d+|\d+", coord)
    if not num:
        return None
    val = float(num[0])

    # Determine sign based on hemisphere
    if "S" in coord.upper() or "W" in coord.upper():
        val = -val
    return val

df1['Latitude'] = df1['Latitude'].apply(clean_coordinate)
df1['Longitude'] = df1['Longitude'].apply(clean_coordinate)

df['AFLA (ppb)'].isna().sum()

df1['afla1']=df['AFLA (ppb)']

print(df1[['Country','Latitude','Longitude']].head(20))
df1['Country'].unique()

if 's' in df.loc[df['Country'] == 'kenya', 'Longitude'].astype('str').str.lower().str.split(''):
  print()

df.loc[df['Country'] == 'kenya', 'Longitude'].str.lower().str.split('')

if df.loc[df['Country'] == 'kenya', 'Longitude'].astype('str').str.lower().str.contains('s').any():
  df1.loc[df1['Country'] == 'kenya', ['Latitude']] *= -1
  print('yes')

print('Kenya Coordinates:')
print(df1.loc[df1['Country'] == 'kenya', ['Latitude', 'Longitude']].head(26))

df1.loc[df1['Country'] == 'southafrica', ['Latitude']] *= -1
df1.loc[df1['Country'] == 'cotedvore', ['Longitude']] *= -1

print('Kenya Coordinates:')
print(df1.loc[df1['Country'] == 'kenya', ['Latitude', 'Longitude']].head(10))
print('\nSouth Africa Coordinates:')
print(df1.loc[df1['Country'] == 'southafrica', ['Latitude', 'Longitude']].head(10))
print('\nic Coordinates:')
print(df1.loc[df1['Country'] == 'cotedvore', ['Latitude', 'Longitude']].head(20))

df.columns
df1.loc[df1['Country'] == 'cotedvore', ['Harvestdate']] = df.loc[df['Country'] == 'cotedvore', ['SamplingDate']]

df1.tail(20)
print(df1.loc[df1['Country'] == 'cotedvore', ['Harvestdate']])
df.loc[df['Country'] == 'cotedvore', ['SamplingDate']]

# sav ethe df1
df1.to_csv('cleaned_2024pa.csv', index=False)

print(df1.loc[df1['Country']=='kenya', ['Latitude','Longitude']])

# get data fro country Benin

benin_data = uprise_data[uprise_data["Country"] == "Benin"]
nigeria_data = uprise_data[uprise_data["Country"] == "Nigeria"]
kenya_data = uprise_data[uprise_data["Country"] == "Kenya"]
southafrica_data = uprise_data[uprise_data["Country"] == "SouthAfrica"]
coteDvore_data = uprise_data[uprise_data["Country"] == "CoteDvore"]

print(f" kenya = {kenya_data.shape}")
print(f" nigeria = {nigeria_data.shape}")
print(f" southafrica = {southafrica_data.shape}")
print(f" coteDvore = {coteDvore_data.shape}")
print(f" Benin = {benin_data.shape}")

print(f"total = {uprise_data.shape}")
print(f"cummulative = {benin_data.shape[0] + kenya_data.shape[0] + nigeria_data.shape[0] + southafrica_data.shape[0] + coteDvore_data.shape[0]}")

benin_data['Variety'].value_counts().sum()
benin_data['Variety'].unique()

benin_data.info()
print(benin_data)
benin_data.describe()

benin_data = benin_data.drop(columns=benin_data.columns[28:], axis=1)

import requests

def getweather( lat, lon, start_date, end_date):
  url = "https://power.larc.nasa.gov/api/temporal/daily/point?start={start_date}&end={end_date}&latitude={lat}&longitude={lon}&parmeters=T2M,PRECTOT,RH2M&community=AG&format=JSON"
  response = requests.get (url)
  data = response.json()
  return (data)

wdata= getweather(25.5300, 28.85775, "20241101", "20250630")

wdata.keys()

from tensorflow.keras import Model, layers



import pandas as pd

dfw = pd.read_csv('/content/2024pw.csv')
dfs = pd.read_csv('/content/2024ps.csv')
dfa = pd.read_csv('/content/cleaned_2024pa.csv')



print(len(dfw))
print(len(dfs))
print(len(dfa))

#dfw.drop(columns=['Harvestdate','Sowdate'], inplace=True)

print(dfw.columns)
print(dfs.columns)
print(dfa.columns)

dfw.fillna(dfw.mean(numeric_only=True), inplace=True)

# remove duplicate coordinates
dfw = dfw.groupby(['Longitude','Latitude']).mean(numeric_only=True).reset_index()
print(len(dfw))
#dfa = dfa.groupby(['Longitude','Latitude']).mean(numeric_only=True).reset_index()


# merge
dfg1 = pd.merge(dfs, dfw, on=['Longitude','Latitude'], how='inner')
print(len(dfg1))

dfg = pd.merge(dfa, dfg1, on=['Longitude','Latitude'], how='inner')

print(dfg.shape)
print(dfg.head())
print(dfg.columns)

dfg.to_csv('2024pg.csv', index=False)

import requests
import pandas as pd

# === USER INPUT ===
latitude = -25.5300
longitude = 28.85775
start = 20241101
end = 20250630
parameters = ["T2M", "PRECTOTCORR", "RH2M", "ALLSKY_SFC_SW_DWN"]  # Temp, rainfall, humidity, solar radiation

# === API URL ===
url = (
    f"https://power.larc.nasa.gov/api/temporal/daily/point"
    f"?parameters={','.join(parameters)}"
    f"&community=AG"
    f"&longitude={longitude}"
    f"&latitude={latitude}"
    f"&start={start}"
    f"&end={end}"
    f"&format=JSON"
)

# === API REQUEST ===
response = requests.get(url)
data = response.json()

# === EXTRACT DATA ===
records = data["properties"]["parameter"]
df = pd.DataFrame(records)
df = df.transpose()
df.reset_index(inplace=True)
df.rename(columns={'index': 'Date'}, inplace=True)



print(df.head())

df.to_csv("nasa_weather_.csv", index=False)
print("✅ Data saved to nasa_power_weather_data.csv")

data["properties"]

param_info = data['properties']['parameterInformation']
print(param_info['T2M']['longname'], "-", param_info['T2M']['units'])

sites = pd.read_csv("/content/UPRISE Data Collection_v.csv", encoding='latin-1')

sites.head()

sites['Lat'] = sites['Longitude']
sites['Lon'] = sites['Latitude']
sites.iloc[:10,:]

## CLEAN DATES ##


import pandas as pd
import calendar
from datetime import datetime

# === Helper function to convert mixed month-year strings ===
def convert_to_date(date_str, is_start=True):
    if pd.isna(date_str) or str(date_str).strip() in ["NotApplied", "", "nan"]:
        return pd.NaT

    date_str = str(date_str).strip()

    # Try both common patterns
    for fmt in ("%b-%y", "%y-%b", "%d-%b", "%b-%d"):
        try:
            date = datetime.strptime(date_str, fmt)
            break
        except ValueError:
            continue
    else:
        print(f"⚠️ Could not parse date: {date_str}")
        return pd.NaT

    # If parsed only month & year (no day), assign start or end of month
    if date.day == 1 and fmt in ("%b-%y", "%y-%b"):
        if is_start:
            return pd.Timestamp(date.year, date.month, 1)
        else:
            last_day = calendar.monthrange(date.year, date.month)[1]
            return pd.Timestamp(date.year, date.month, last_day)

    # Otherwise, return parsed full date
    return pd.Timestamp(date)

# === Apply conversions ===
sites["sowing_start"] = sites["SowingDate"].apply(lambda x: convert_to_date(x, is_start=True))
sites["harvest_end"] = sites["HarvestDate"].apply(lambda x: convert_to_date(x, is_start=False))

# === Example Output ===
print(sites[["SowingDate", "sowing_start", "HarvestDate", "harvest_end"]].head())

## CLEAN COORDINATES ##


import pandas as pd
import re


# === Function to clean coordinates ===
def clean_coordinate(coord):
    if pd.isna(coord):
        return None
    # Extract numeric part
    num = re.findall(r"[-+]?\d*\.\d+|\d+", coord)
    if not num:
        return None
    val = float(num[0])

    # Determine sign based on hemisphere
    if "S" in coord.upper() or "W" in coord.upper():
        val = -val
    return val

# === Apply the cleaning ===
#sites["longitude_clean"] = benin_data["Longitude"].apply(clean_coordinate)
#sites["latitude_clean"] = benin_data["Latitude"].apply(clean_coordinate)

lon = benin_data["Longitude"].apply(clean_coordinate)
lat = benin_data["Latitude"].apply(clean_coordinate)

print(lon)
print(lat)
#
# The following line caused the error by trying to convert a Series to a single Timestamp.
# If the goal was to convert the column, use pd.to_datetime. If to print one value, pick an element.
# print(pd.Timestamp(benin_data['SowingDate']))

site_ubset=['latitude_clean', 'longitude_clean', 'sowing_start', 'harvest_end']

sites[site_ubset]

new_sites[site_ubset]

import pandas as pd
import requests
import time
from tqdm import tqdm
import numpy as np

# === Keep only unique rows ===
new_sites = sites.drop_duplicates(
    subset=['latitude_clean', 'longitude_clean', 'sowing_start', 'harvest_end']
).reset_index(drop=True)
print(f"✅ Unique sites to fetch: {len(new_sites)}")

parameters = ["T2M", "PRECTOTCORR", "RH2M", "ALLSKY_SFC_SW_DWN"]

all_data = []

def fetch_nasa_power(lat, lon, start, end):

    if pd.isna(lat) or pd.isna(lon) or pd.isna(start) or pd.isna(end):
        return None

    start_str = start.strftime('%Y%m%d')
    end_str = end.strftime('%Y%m%d')

    url = (
        f"https://power.larc.nasa.gov/api/temporal/daily/point?"
        f"parameters={','.join(parameters)}"
        f"&community=AG"
        f"&longitude={lon}"
        f"&latitude={lat}"
        f"&start={start_str}"
        f"&end={end_str}"
        f"&format=JSON"
    )

    try:
        response = requests.get(url, timeout=60)
        data = response.json()

        if "properties" not in data or "parameter" not in data["properties"]:
            return None

        params = data["properties"]["parameter"]

        # Convert to a DataFrame of daily values
        daily_df = pd.DataFrame(params).T
        daily_df.index = pd.to_datetime(daily_df.index, format='%Y%m%d')
        daily_df = daily_df.sort_index()

        # 🟦 WEEKLY AGGREGATION: Sum over each 7-day block
        weekly_df = daily_df.resample("W").sum()   # change to .mean() if needed

        # 🟧 RENAME COLUMNS: T2M_wk1, T2M_wk2, etc.
        weekly_df.columns = [
            f"{col}_wk{i+1}" for col in weekly_df.columns for i in range(len(weekly_df))
        ][:len(weekly_df.columns) * len(weekly_df)]

        # Fix column naming
        new_cols = {}
        for col in weekly_df.columns:
            base, wk = col.split("_wk")
            # create week index based on actual column order
            if base not in new_cols:
                new_cols[base] = 1
            new_val = f"{base}_wk{new_cols[base]}"
            new_cols[base] += 1
            weekly_df.rename(columns={col: new_val}, inplace=True)

        # Flatten to one row
        flat_row = {"latitude": lat, "longitude": lon, "sowing_start": start, "harvest_end": end}
        flat_row.update(weekly_df.to_dict("records")[0])  # add week values

        return flat_row

    except Exception as e:
        print(f"❌ Error: {e}")
        return None


# === Retrieve for all sites ===
for idx, row in tqdm(new_sites.iterrows(), total=len(new_sites)):
    lat, lon = row["latitude_clean"], row["longitude_clean"]
    start, end = row["sowing_start"], row["harvest_end"]

    data_row = fetch_nasa_power(lat, lon, start, end)

    if data_row:
        all_data.append(data_row)
        print(f"✅ Site {idx+1}/{len(new_sites)} downloaded.")

    time.sleep(2)  # NASA rate limit


# === Save output ===
if all_data:
    final_df = pd.DataFrame(all_data)
    final_df.to_csv("All_Sites_WeatherData_WEEKLY.csv", index=False)
    print("🎉 Weekly aggregated dataset saved: All_Sites_WeatherData_WEEKLY.csv")
else:
    print("⚠️ No data retrieved.")

## RETRIEVE WEATHER DATA ##


import pandas as pd
import requests
import time
from tqdm import tqdm

# === Keep only unique rows based on lat, lon, start, end ===
new_sites = sites.drop_duplicates(
    subset=['latitude_clean', 'longitude_clean', 'sowing_start', 'harvest_end']
).reset_index(drop=True)
print(f"✅ Unique sites to fetch: {len(new_sites)}")

# === Define weather parameters ===
parameters = ["T2M","PRECTOTCORR", "RH2M", "ALLSKY_SFC_SW_DWN"]

# === Container for all flattened rows ===
all_data = []

def fetch_nasa_power(lat, lon, start, end):
    """Fetch and flatten NASA POWER weather data for one site into a single-row dict"""
    if pd.isna(lat) or pd.isna(lon) or pd.isna(start) or pd.isna(end):
        print(f"⚠️ Missing lat/lon or dates for ({lat}, {lon})")
        return None

    # Format dates
    start_str = start.strftime('%Y%m%d')
    end_str = end.strftime('%Y%m%d')

    # === Construct API URL ===
    url = (
        f"https://power.larc.nasa.gov/api/temporal/daily/point?"
        f"parameters={','.join(parameters)}"
        f"&community=AG"
        f"&longitude={lon}"
        f"&latitude={lat}"
        f"&start={start_str}"
        f"&end={end_str}"
        f"&format=JSON"
    )

    try:
        response = requests.get(url, timeout=60)
        data = response.json()

        if "properties" not in data or "parameter" not in data["properties"]:
            print(f"⚠️ No data for ({lat}, {lon}) from {start_str} to {end_str}.")
            return None

        # === Extract data ===
        params = data["properties"]["parameter"]

        # === Flatten the daily data into one row ===
        flat_row = {
            "latitude": lat,
            "longitude": lon,
            "sowing_start": start,
            "harvest_end": end
        }

        for param, date_values in params.items():
            for date_str, value in date_values.items():
                flat_row[f"{param}_{date_str}"] = value

        return flat_row

    except Exception as e:
        print(f"❌ Error fetching data for ({lat}, {lon}) from {start_str} to {end_str}: {e}")
        return None


# === Loop through each site and collect flattened rows ===
for idx, row in new_sites.iterrows():
    lat = row["latitude_clean"]
    lon = row["longitude_clean"]
    start = row["sowing_start"]
    end = row["harvest_end"]

    data_row = fetch_nasa_power(lat, lon, start, end)
    if data_row:
        all_data.append(data_row)
        print(f"✅ Added site {idx+1}/{len(new_sites)}: ({lat}, {lon})")

    time.sleep(2)  # Respect NASA POWER rate limit


# === Combine all into one DataFrame and save ===
if all_data:
    final_df = pd.DataFrame(all_data)
    output_file = "All_Sites_WeatherData.csv"
    final_df.to_csv(output_file, index=False)
    print(f"\n✅ All data saved successfully: {output_file}")
else:
    print("\n⚠️ No data retrieved.")

## SOIL DATA RETRIEVAL ##


import pandas as pd
import requests
import time
from tqdm import tqdm

# === API details ===
base_url = "https://api.isda-africa.com"
username = "mohammed.merhdie@gmail.com"
password = "P13bs1019"

# === Authenticate to get token ===
payload = {"username": username, "password": password}
response = requests.post(f"{base_url}/login", data=payload)

if response.status_code != 200:
    raise Exception(f"❌ Login failed: {response.text}")

access_token = response.json().get("access_token")
if not access_token:
    raise Exception("❌ No access token returned. Check credentials.")

headers = {"Authorization": f"Bearer {access_token}"}

# === Soil properties to request ===
soil_properties = [
    # Soil chemical properties
    "ph",                           # pH
    "carbon_organic",               # Organic carbon (SOC)
    "carbon_total",                 # Total carbon
    "nitrogen_total",               # Total nitrogen
    "cation_exchange_capacity",     # Effective CEC
    "phosphorous_extractable",      # Available phosphorus
    "potassium_extractable",        # Available potassium
    "calcium_extractable",          # Available calcium
    "magnesium_extractable",        # Available magnesium
    "iron_extractable",             # Available iron
    "zinc_extractable",             # Available zinc
    "sulphur_extractable",          # Available sulphur

    # Soil physical properties
    "sand_content",                 # % Sand
    "silt_content",                 # % Silt
    "clay_content",                 # % Clay
    "stone_content",                # % Stones
    "bulk_density",                 # g/cm³, affects aeration
]


depth = "0-20"  # cm layer
soil_data = []

# === Remove duplicate sites ===
unique_sites = sites.drop_duplicates(subset=["latitude_clean", "longitude_clean"]).reset_index(drop=True)
print(f"✅ Fetching soil data for {len(unique_sites)} unique sites")


# === Loop through each coordinate ===
for idx, row in unique_sites.iterrows():
    lat = row["latitude_clean"]
    lon = row["longitude_clean"]

    site_info = {"latitude": lat, "longitude": lon}

    # === Retrieve each soil property ===
    for prop in soil_properties:
        try:
            url = f"{base_url}/isdasoil/v2/soilproperty?lat={lat}&lon={lon}&property={prop}&depth={depth}"
            r = requests.get(url, headers=headers, timeout=60)

            if r.status_code == 200:
                data = r.json()
                if "property" in data and prop in data["property"]:
                    value = data["property"][prop][0]["value"]["value"]
                    site_info[prop] = value
                else:
                    site_info[prop] = None
            else:
                print(f"⚠️ {prop} failed for ({lat},{lon}) → {r.status_code} -skipping")
                site_info[prop] = None
                continue

            time.sleep(3)  # prevent hitting rate limits

        except Exception as e:
            print(f"❌ Error fetching {prop} for ({lat},{lon}): {e}")
            site_info[prop] = None

    soil_data.append(site_info)

# === Combine into DataFrame and save ===
soil_df = pd.DataFrame(soil_data)
soil_df.to_csv("ISDA_Soil_Data_AllSites.csv", index=False)
print("✅ Soil data saved to ISDA_Soil_Data_AllSites.csv")

import pandas as pd
df = pd.read_csv('/content/cleaned_2024pa.csv')

import pandas as pd
import requests
import time
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed

# =========================
# API DETAILS
# =========================

base_url = "https://api.isda-africa.com"

username = "mohammed.merhdie@gmail.com"
password = "P13bs1019"

payload = {"username": username, "password": password}

response = requests.post(f"{base_url}/login", data=payload)

if response.status_code != 200:
    raise Exception(f"Login failed: {response.text}")

access_token = response.json().get("access_token")

headers = {"Authorization": f"Bearer {access_token}"}

print("Login successful")

# =========================
# SOIL VARIABLES
# =========================

soil_properties = [

    "ph",
    "carbon_organic",
    "carbon_total",
    "nitrogen_total",
    "cation_exchange_capacity",
    "phosphorous_extractable",
    "potassium_extractable",
    "calcium_extractable",
    "magnesium_extractable",
    "iron_extractable",
    "zinc_extractable",
    "sulphur_extractable",

    "sand_content",
    "silt_content",
    "clay_content",
    "stone_content",
    "bulk_density",
]

depth = "0-20"

# =========================
# UNIQUE LOCATIONS
# =========================

unique_sites = df[["Latitude", "Longitude"]].drop_duplicates().reset_index(drop=True)

print(f"Fetching soil data for {len(unique_sites)} locations")

# =========================
# FUNCTION TO FETCH SOIL DATA
# =========================

def fetch_soil(lat, lon):

    site_data = {
        "Latitude": lat,
        "Longitude": lon
    }

    for prop in soil_properties:

        retries = 3

        for attempt in range(retries):

            try:

                url = (
                    f"{base_url}/isdasoil/v2/soilproperty?"
                    f"lat={lat}&lon={lon}&property={prop}&depth={depth}"
                )

                r = requests.get(url, headers=headers, timeout=15)

                if r.status_code == 200:

                    data = r.json()

                    if "property" in data and prop in data["property"]:

                        value = data["property"][prop][0]["value"]["value"]
                        site_data[prop] = value
                        break

                    else:
                        site_data[prop] = None
                        break

                else:
                    time.sleep(1)

            except Exception:
                time.sleep(1)

        else:
            site_data[prop] = None

    # small pause to avoid API bursts
    time.sleep(0.1)

    return site_data


# =========================
# PARALLEL DOWNLOAD
# =========================

soil_rows = []

with ThreadPoolExecutor(max_workers=6) as executor:

    futures = [
        executor.submit(fetch_soil, row.Latitude, row.Longitude)
        for row in unique_sites.itertuples(index=False)
    ]

    for future in tqdm(as_completed(futures), total=len(futures)):
        soil_rows.append(future.result())


# =========================
# CREATE DATAFRAME
# =========================

soil_df = pd.DataFrame(soil_rows)

print("Soil download finished")

# =========================
# SAVE SOIL DATA
# =========================

soil_df.to_csv("2024ps.csv", index=False)

print("Soil data saved")


# ===

# fill missing soil values base on spatial interpolation

import pandas as pd
soil_df = pd.read_csv('/content/2024ps.csv')
import pandas as pd
import numpy as np
from scipy.spatial import KDTree

# Columns that contain soil variables
soil_cols = [
    "ph","carbon_organic","carbon_total","nitrogen_total",
    "cation_exchange_capacity","phosphorous_extractable",
    "potassium_extractable","calcium_extractable",
    "magnesium_extractable","iron_extractable",
    "zinc_extractable","sulphur_extractable",
    "sand_content","silt_content","clay_content",
    "stone_content","bulk_density"
]

# Coordinates
coords = soil_df[["Latitude","Longitude"]].values

# Build KDTree
tree = KDTree(coords)

# Loop through each soil variable
for col in soil_cols:

    # rows with missing values
    missing = soil_df[col].isna()

    if missing.sum() == 0:
        continue

    # rows with known values
    known_points = soil_df.loc[~missing, ["Latitude","Longitude"]].values
    known_values = soil_df.loc[~missing, col].values

    # build KDTree for known points
    known_tree = KDTree(known_points)

    # coordinates needing interpolation
    missing_points = soil_df.loc[missing, ["Latitude","Longitude"]].values

    # find nearest neighbour
    dist, idx = known_tree.query(missing_points, k=1)

    # assign nearest value
    soil_df.loc[missing, col] = known_values[idx]

print("Spatial interpolation completed.")
print(soil_df.isna().sum())
soil_df.to_csv("2024ps.csv", index=False)



import pandas as pd
import requests
import time
from tqdm import tqdm
import numpy as np

parameters = ["T2M", "PRECTOTCORR", "RH2M", "ALLSKY_SFC_SW_DWN"]

def fetch_nasa_power(lat, lon, sow, harvest):

    if pd.isna(lat) or pd.isna(lon) or pd.isna(sow) or pd.isna(harvest):
        return None

    # fetch wider window to cover all needed days
    start = sow - pd.Timedelta(days=5)
    end = harvest

    start_str = start.strftime('%Y%m%d')
    end_str = end.strftime('%Y%m%d')

    url = (
        f"https://power.larc.nasa.gov/api/temporal/daily/point?"
        f"parameters={','.join(parameters)}"
        f"&community=AG"
        f"&longitude={lon}"
        f"&latitude={lat}"
        f"&start={start_str}"
        f"&end={end_str}"
        f"&format=JSON"
    )

    try:

        r = requests.get(url, timeout=60)
        data = r.json()

        params = data["properties"]["parameter"]

        daily = pd.DataFrame(params)
        daily.index = pd.to_datetime(daily.index, format="%Y%m%d")
        daily = daily.sort_index()

        row_out = {}

        # ===============================
        # 1️⃣ SOWING WINDOW (-3 → +30 days)
        # ===============================
        sow_window = daily.loc[sow - pd.Timedelta(days=3): sow + pd.Timedelta(days=30)]

        for i, (_, day) in enumerate(sow_window.iterrows(), start=1):
            for p in parameters:
                row_out[f"{p}_s{i}"] = day[p]

        # ===============================
        # 2️⃣ HARVEST WINDOW (-30 → 0)
        # ===============================
        harvest_window = daily.loc[harvest - pd.Timedelta(days=29): harvest]

        for i, (_, day) in enumerate(harvest_window.iterrows(), start=1):
            for p in parameters:
                row_out[f"{p}_h{i}"] = day[p]

        # ===============================
        # 3️⃣ MIDDLE GROWTH WINDOW
        # ===============================
        mid_start = sow + pd.Timedelta(days=31)
        mid_end = harvest - pd.Timedelta(days=31)

        mid = daily.loc[mid_start:mid_end]

        if len(mid) > 0:

            segments = np.array_split(mid, 30)

            for i, seg in enumerate(segments, start=1):

                for p in parameters:

                    row_out[f"{p}_g{i}"] = seg[p].mean()

        return row_out

    except Exception as e:
        print("Error:", e)
        return None


# ===================================
# LOOP THROUGH OBSERVATIONS
# ===================================

weather_rows = []

for idx, row in tqdm(df.iterrows(), total=len(df)):

    lat = row["Latitude"]
    lon = row["Longitude"]
    sow = pd.to_datetime(row["Sowdate"])
    har = pd.to_datetime(row["Harvestdate"])

    data = fetch_nasa_power(lat, lon, sow, har)

    if data:
        data["Latitude"] = lat
        data["Longitude"] = lon
        data["Sowdate"] = sow
        data["Harvestdate"] = har

        weather_rows.append(data)

    time.sleep(1)

weather_df = pd.DataFrame(weather_rows)

weather_df.to_csv("2024pw.csv", index=False)

print("✅ Weather features generated.")

import requests

username = "mohammed.merhdie@gmail.com"
password = "P13bs1019"

base_url = "https://api.isda-africa.com"

# First call the login endpoint to get the access token. Token expiry: 60 minutes
payload = {"username": username, "password": password}
response = requests.post(f"{base_url}/login", data=payload)

# Check if login was successful
if response.status_code == 200:
    access_token = response.json().get("access_token")

    if access_token:
        # Then use the access token to call the soilproperty endpoint. Get the ph value for a location in Kenya at 0-20cm depth.
        headers = {"Authorization": f"Bearer {access_token}"}
        response = requests.get(
            f"{base_url}/isdasoil/v2/soilproperty?lat=-0.7196&lon=35.2400&property=ph&depth=0-20",
            headers=headers,
        )

        # Check if the soil data request was successful
        if response.status_code == 200:
            response_data = response.json()

            # Check if 'property' key exists before accessing it
            if 'property' in response_data and 'ph' in response_data['property']:
                print(f"ph value: {response_data['property']['ph'][0]['value']['value']}"
                    f" (uncertainty: {response_data['property']['ph'][0]['uncertainty'][1]['lower_bound']}-"
                    f"{response_data['property']['ph'][0]['uncertainty'][1]['upper_bound']})")
            else:
                print("Error: 'property' or 'ph' key not found in the soil data response.")
                print(f"Soil data response: {response_data}")
        else:
            print(f"Error fetching soil data: API returned status code {response.status_code}")
            print(f"Soil data response text: {response.text}")
    else:
        print("Error: Access token not found in the login response.")
        print(f"Login response: {response.json()}")
else:
    print(f"Error logging in to the API: API returned status code {response.status_code}")
    print(f"Login response text: {response.text}")

import requests
import pandas as pd

# --- Coordinates ---
latitude = -1.2921     # example: Nairobi, Kenya
longitude = 36.8219

# --- Define soil properties to retrieve ---
properties = ["clay", "sand", "silt", "phh2o", "nitrogen", "soc", "cec"]
depths = ["0-5cm", "5-15cm", "15-30cm"]

# --- Build API URL ---
url = (
    f"https://rest.isric.org/soilgrids/v2.0/properties/query?"
    f"lon={longitude}&lat={latitude}"
    f"&property={','.join(properties)}"
    f"&depth={','.join(depths)}&value=mean"
)

# --- Fetch data ---
response = requests.get(url)

# --- Check for successful response before parsing JSON ---
if response.status_code != 200:
    print(f"Error: API returned status code {response.status_code}")
    print(f"Response text: {response.text}")
else:
    try:
        data = response.json()

        # --- Flatten the data into a dictionary ---
        flat = {"latitude": latitude, "longitude": longitude}

        for layer in data["properties"]["layers"]:
            prop = layer["name"]
            for d in layer["depths"]:
                depth_label = d["label"].replace(" ", "").replace("-", "_")
                flat[f"{prop}_{depth_label}"] = d["values"]["mean"]

        # --- Display as DataFrame ---
        df = pd.DataFrame([flat])
        print(df.T)

    except requests.exceptions.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        print(f"Response text: {response.text}")

!pip install azure-ai-ml

from azure.ai.ml import MLClient



from google.colab import drive
drive.mount('/content/drive')